name: Run tests using Jest and React Testing Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
        shell: bash
      - name: Run unit tests
        run: npm run test
        shell: bash
