version: '3.9'

services:
  postgres:
    image: postgres:14.3
    command: ['postgres', '-c', 'log_statement=all']
    restart: always
    container_name: expense_reports_db
    env_file:
      - .env.local
    ports:
      - '5433:5432'
