name: Run checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
        shell: bash
      - name: Run eslint
        run: npm run lint

  prettier:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
        shell: bash
      - name: Run prettier
        run: npm run prettier

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
        shell: bash
      - name: Run unit tests
        run: npm run test
        shell: bash
